name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 165.227.129.205
        key: ${{ secrets.SSH_KEY }}
        username: root
        script: |
              cd app
              git remote add origin git@github.com:Cut-it-Business/auto_tests.git
              git pull origin main
              git checkout main -f
              git branch --set-upstream-to origin/main
              docker compose down
              docker compose build
              docker compose up -d
